version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - env/.app.env
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - ./app:/home/python/app
