version: "3.7"

services:
  web:
    image: nginx:1.18.0
    env_file:
      - env/.nginx.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certs:/certs
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - env/.app.env
